### ISSUE TITLE
can't unsafeBitCast between types of different sizes

### ISSUE THREAD

**Issue by lluisgerard** [Roobiq/RBQSafeRealmObject#7]
Since swift 3.0 I've been having this issue.

In `SafeObject`'s function:

```swift
public func object() -> T {
    return unsafeBitCast(self.rbqSafeRealmObject.rlmObject(), to: T.self)
}
```

Fails with `fatal error: can't unsafeBitCast between types of different sizes`

The only way to solve this is to change the `object()` function to:
```swift
public func object() -> T {
    guard let object = self.rbqSafeRealmObject.rlmObject() as? T else {
        return T() // This is actually never called 
    }
    return object
}
```

I'm not sure why the need of `unsafeBitCast` in this case and why is not working. Maybe if someone can point me to the right direction so I can understand why the use of it.

**Comment by bigfish24** [comment]
to fix:

``` swift
public func object() -> T {
    return unsafeBitCast(self.rbqSafeRealmObject.rlmObject() as! RLMObjectBase, to: T.self)
}
```

**Comment by wieseljonas** [comment]
I have a the same issue with this

```
open func objectAtIndexPath(_ indexPath: IndexPath) -> T? {
    if let rlmObject = self.rbqFetchedResultsController.object(at: indexPath) {
        return unsafeBitCast(rlmObject, to: T.self)
    }      
    return nil
}
```

**Comment by wieseljonas** [comment]
This error was on the controller I did a pull request

**Comment by bigfish24** [comment]
This was fixed in the latest release.
